POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "react course"
}

###

GET http://localhost:3333/courses?orderBy=title

###

GET http://localhost:3333/courses/10e5b7ab-e447-48b3-b05c-11b6aad8ceb7

###
PATCH http://localhost:3333/courses/37ada17e-9903-4351-9465-8b757f6c2016
Content-Type: application/json

{
  "title": "updated react native course"
}

###
DELETE http://localhost:3333/courses/4429fc59-b51d-4ee5-b007-d06c710a736b

