POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de Fastify"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/eac4d267-cec0-42c8-91a7-1207260019f4

