POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de Fastify"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/16b910c1-e9ef-4440-927a-00f127113cb9

###
PATCH http://localhost:3333/courses/16b910c1-e9ef-4440-927a-00f127113cb9
Content-Type: application/json

{
  "title": "Curso de Fastify atualizado"
}

###
DELETE http://localhost:3333/courses/16b910c1-e9ef-4440-927a-00f127113cb9

